/*  File generated by: Map Ed v0.99 */
#include "gba_types.h"

#define bgPaletteSize 512
#define bgTilesSize 7680
#define bgMapLayer0Size 4096
#define bgMapLayer1Size 4096

extern const u16 bgPalette[256];
extern const u16 bgTiles[3840];
extern const u16 bgMapLayer0[2048];
extern const u16 bgMapLayer1[2048];
extern const u16 bgCollision[2048];
