/*  File generated by: Map Ed v0.99 */

#include "gba_types.h"

#define bgPaletteSize 512
#define bgTilesSize 2144

extern const u16 bgPalette[256];
extern const u16 bgTiles[1072];
extern const u16 bgMap[2048];
extern const u16 bgCollision[2048];
